### PR TITLE
Dockerfile: Install genpolicy tool

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by surajssd** [comment]
cc: @arc9693

**Review by arc9693 — COMMENTED** [review]
genpolicy tool takes a default settings and rules.rego file. we should probably copy those as well.

**Comment by surajssd** [comment]
Do you mean this: https://github.com/kata-containers/kata-containers/blob/main/src/tools/genpolicy/genpolicy-settings.json and this? https://github.com/kata-containers/kata-containers/blob/main/src/tools/genpolicy/rules.rego

**Comment by arc9693** [comment]
> Do you mean this: https://github.com/kata-containers/kata-containers/blob/main/src/tools/genpolicy/genpolicy-settings.json and this? https://github.com/kata-containers/kata-containers/blob/main/src/tools/genpolicy/rules.rego

yes

**Comment by surajssd** [comment]
I added the `genpolicy-settings.json` into the config of demo3 so that it can work from within the docker container and on the regular host.

**Comment by surajssd** [comment]
And since we have rego rules in the demo3 I didn't include: [rules.rego](https://github.com/kata-containers/kata-containers/blob/main/src/tools/genpolicy/rules.rego)

**Comment by surajssd** [comment]
To run the set of commands from within the docker you can do `make docker-build` and `make docker-run`.

**Review by arc9693 — APPROVED** [review]
LGTM

**Pull request merged**
